# Generated by Django 3.1.6 on 2021-04-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_data',
            name='address',
        ),
        migrations.AddField(
            model_name='air_data',
            name='image',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
