# Generated by Django 3.1.6 on 2021-04-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_air_data_distance_travelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_data',
            name='service_required',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
