# Generated by Django 3.1.6 on 2021-04-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_air_data_service_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_data',
            name='last_service_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
