# Generated by Django 3.1.6 on 2021-04-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_air_data_last_service_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air_data',
            old_name='age',
            new_name='company',
        ),
    ]
