# Generated by Django 3.1.6 on 2021-04-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210430_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='air_data',
            old_name='company',
            new_name='no_of_flights',
        ),
        migrations.AddField(
            model_name='air_data',
            name='base_station',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
