# Generated by Django 3.1.6 on 2021-04-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210430_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_data',
            name='food',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
