# Generated by Django 3.1.6 on 2021-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_air_data_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_data',
            name='food',
        ),
        migrations.AddField(
            model_name='air_data',
            name='continental',
            field=models.CharField(default='No', max_length=30),
        ),
        migrations.AddField(
            model_name='air_data',
            name='jain',
            field=models.CharField(default='No', max_length=30),
        ),
        migrations.AddField(
            model_name='air_data',
            name='non_veg',
            field=models.CharField(default='No', max_length=30),
        ),
        migrations.AddField(
            model_name='air_data',
            name='veg',
            field=models.CharField(default='No', max_length=30),
        ),
    ]
