# Generated by Django 3.1.6 on 2021-05-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210430_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_data',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
