# Generated by Django 3.1.6 on 2021-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210501_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air_data',
            name='image',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
