# Generated by Django 3.1.6 on 2021-05-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210502_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air_data',
            name='continental',
        ),
        migrations.RemoveField(
            model_name='air_data',
            name='jain',
        ),
        migrations.RemoveField(
            model_name='air_data',
            name='non_veg',
        ),
        migrations.RemoveField(
            model_name='air_data',
            name='veg',
        ),
        migrations.AddField(
            model_name='air_data',
            name='accept',
            field=models.CharField(default='No', max_length=30),
        ),
    ]
